# Generated by Django 6.0.4 on 2026-04-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FirewallRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")], max_length=8
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "protocol",
                    models.CharField(
                        choices=[("any", "Any"), ("tcp", "TCP"), ("udp", "UDP")],
                        default="any",
                        max_length=8,
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=100)),
                ("enabled", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, default="", max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
    ]
